name: Profile Metrics - Overview
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Overview
        uses: lowlighter/metrics@latest
        with:
          filename: overview.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Sadab-Ansari
          template: classic
          base: activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
